### PR TITLE
opam needs bubblewrap on linux

### PR DESCRIPTION
**Pull request by peterjc**
Since opam 2.0.0~rc2, opam uses bwrap on Linux, see:

https://opam.ocaml.org/doc/FAQ.html#Why-does-opam-require-bwrap

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
@conda-forge-admin, please rerender

**Comment by fasiha** [comment]
@peterjc this looks good to me but I unfortunately don't have an easy way to test it. Are you ok with a rubberstamp approval?

**Comment by peterjc** [comment]
Sounds good to me - Earlier today I installed ``opam`` from conda, and when running it got a message about it needing bubblewrap.

**Review by fasiha — APPROVED** [review]

**Comment by peterjc** [comment]
OK to merge?

**Comment by fasiha** [comment]
Yup go for it, I’m just not sure if we should merge or squash or if there’s a right answer 😅 so I leave it to you 🙇

**Comment by peterjc** [comment]
Thank you!

**Pull request merged**
